In [14]:
import binascii
import numpy as np

In [28]:
filename = 'pt.dat'
with open(filename, 'rb') as f:
    content = f.read()
pt=str(binascii.hexlify(content))[2:]
pt=[''.join([pt[16*i+2*j:16*i+2*j+2] for j in range(7,-1,-1)]) for i in range(len(pt)//16)]
print(pt[:256])

['aed66ce184be2309', 'aed66ce184be2319', 'aed66ce184be2329', 'aed66ce184be2339', 'aed66ce184be2349', 'aed66ce184be2359', 'aed66ce184be2369', 'aed66ce184be2379', 'aed66ce184be2389', 'aed66ce184be2399', 'aed66ce184be23a9', 'aed66ce184be23b9', 'aed66ce184be23c9', 'aed66ce184be23d9', 'aed66ce184be23e9', 'aed66ce184be23f9', 'aed66ce184be2320', 'aed66ce184be2321', 'aed66ce184be2322', 'aed66ce184be2323', 'aed66ce184be2324', 'aed66ce184be2325', 'aed66ce184be2326', 'aed66ce184be2327', 'aed66ce184be2328', 'aed66ce184be2329', 'aed66ce184be232a', 'aed66ce184be232b', 'aed66ce184be232c', 'aed66ce184be232d', 'aed66ce184be232e', 'aed66ce184be232f', 'aed66ce184be0329', 'aed66ce184be1329', 'aed66ce184be2329', 'aed66ce184be3329', 'aed66ce184be4329', 'aed66ce184be5329', 'aed66ce184be6329', 'aed66ce184be7329', 'aed66ce184be8329', 'aed66ce184be9329', 'aed66ce184bea329', 'aed66ce184beb329', 'aed66ce184bec329', 'aed66ce184bed329', 'aed66ce184bee329', 'aed66ce184bef329', 'aed66ce184be2029', 'aed66ce184be2129',

In [29]:
filename = 'ct.dat'
with open(filename, 'rb') as f:
    content = f.read()
ct=str(binascii.hexlify(content))[2:]
ct=[''.join([ct[16*i+2*j:16*i+2*j+2] for j in range(7,-1,-1)]) for i in range(len(ct)//16)]
print(ct[:256])

['c0076eba0e10d150', '3b3a30df056597a4', 'b554cab59d2733a9', 'f5c216cdce16be64', 'e1c485a5c250acd5', 'e0c049c96b783355', '8895172075557404', '56334c292ff68504', '78506891847c4eee', '11e6a9cf815880bc', '809dbc1682f2bf00', '00ce52baf5660929', 'f0c4e9c181168fe0', 'b778aba29270837b', '5309bbe19ced3f49', '342b454060dc27eb', 'a0a129a70aafab25', 'db58d4d6bced8bc2', '2a74b9cbc4437153', 'c2ba5a672857790e', 'f352c54f2f4655ba', 'b2631da0e02c5ac0', 'd526ff6a6d714f83', '4bdc274bf99e24ed', '39e4920ef10fe378', 'b554cab59d2733a9', '770aae19edd5136c', 'be232e6cf239c893', 'a31f10ea30022129', '39caa4c418f7e995', 'bd50f78e84c10b24', 'fbd7be16f2e0d72b', '2e5cbbcca2e451fa', '66db796dceb9c3e0', 'b554cab59d2733a9', '5daed2a9179cefb4', '8c99c2a1e57b29b7', '5d8df53b4fca5377', 'af34ad7c1cdbcc5f', 'f6635d3f7d9277f9', 'b9454ab6e88c0994', 'b15da2cb62732556', 'fc8b2dfde87a4ab9', 'ba3964e1c4d41fdb', '260e3f69c4422939', '9dbc3200b5330c02', '59ac741d22047c5d', '7c8e98b18fcd5811', '81b1828e59fb901a', '5e5be550475e971e',

In [18]:
p1=[list(i) for i in pt[:16]+pt[256:272]+pt[512:528]+pt[768:784]+pt[1024:1040]]
for i in range(len(p1)):
    p1[i]=['0x'+j for j in p1[i]]
    for j in range(16):
        p1[i][j]=int(eval(p1[i][j]))
print(p1)

[[10, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 0, 9], [10, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 1, 9], [10, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 2, 9], [10, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 3, 9], [10, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 4, 9], [10, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 5, 9], [10, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 6, 9], [10, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 7, 9], [10, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 8, 9], [10, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 9, 9], [10, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 10, 9], [10, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 11, 9], [10, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 12, 9], [10, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 13, 9], [10, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 14, 9], [10, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 15, 9], [14, 11, 14, 9, 11, 11, 15, 1, 15, 1, 4, 9, 9, 0, 0, 2], [14, 11, 14, 9, 11, 11, 

In [19]:
c1=[list(i) for i in ct[:16]+ct[256:272]+ct[512:528]+ct[768:784]+ct[1024:1040]]
for i in range(len(c1)):
    c1[i]=['0x'+j for j in c1[i]]
    for j in range(16):
        c1[i][j]=int(eval(c1[i][j]))
print(c1)

[[12, 0, 0, 7, 6, 14, 11, 10, 0, 14, 1, 0, 13, 1, 5, 0], [3, 11, 3, 10, 3, 0, 13, 15, 0, 5, 6, 5, 9, 7, 10, 4], [11, 5, 5, 4, 12, 10, 11, 5, 9, 13, 2, 7, 3, 3, 10, 9], [15, 5, 12, 2, 1, 6, 12, 13, 12, 14, 1, 6, 11, 14, 6, 4], [14, 1, 12, 4, 8, 5, 10, 5, 12, 2, 5, 0, 10, 12, 13, 5], [14, 0, 12, 0, 4, 9, 12, 9, 6, 11, 7, 8, 3, 3, 5, 5], [8, 8, 9, 5, 1, 7, 2, 0, 7, 5, 5, 5, 7, 4, 0, 4], [5, 6, 3, 3, 4, 12, 2, 9, 2, 15, 15, 6, 8, 5, 0, 4], [7, 8, 5, 0, 6, 8, 9, 1, 8, 4, 7, 12, 4, 14, 14, 14], [1, 1, 14, 6, 10, 9, 12, 15, 8, 1, 5, 8, 8, 0, 11, 12], [8, 0, 9, 13, 11, 12, 1, 6, 8, 2, 15, 2, 11, 15, 0, 0], [0, 0, 12, 14, 5, 2, 11, 10, 15, 5, 6, 6, 0, 9, 2, 9], [15, 0, 12, 4, 14, 9, 12, 1, 8, 1, 1, 6, 8, 15, 14, 0], [11, 7, 7, 8, 10, 11, 10, 2, 9, 2, 7, 0, 8, 3, 7, 11], [5, 3, 0, 9, 11, 11, 14, 1, 9, 12, 14, 13, 3, 15, 4, 9], [3, 4, 2, 11, 4, 5, 4, 0, 6, 0, 13, 12, 2, 7, 14, 11], [10, 9, 15, 0, 10, 10, 13, 8, 12, 12, 7, 13, 6, 7, 11, 3], [1, 15, 2, 11, 11, 12, 12, 9, 10, 5, 12, 10, 1, 7, 7, 10]

In [20]:
rc3='082efa98ec4e6c89'
rc3=list(map(int,[eval('0x'+i) for i in list(rc3)]))
rc2='a4093822299f31d0'
rc2=list(map(int,[eval('0x'+i) for i in list(rc2)]))
rc1='13198a2e03707344'
rc1=list(map(int,[eval('0x'+i) for i in list(rc1)]))
M0=np.array([[0,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
M1=np.array([[1,0,0,0],[0,0,0,0],[0,0,1,0],[0,0,0,1]])
M2=np.array([[1,0,0,0],[0,1,0,0],[0,0,0,0],[0,0,0,1]])
M3=np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,0]])
M0123=np.concatenate((M0,M1,M2,M3),axis=1)
M1230=np.concatenate((M1,M2,M3,M0),axis=1)
M2301=np.concatenate((M2,M3,M0,M1),axis=1)
M3012=np.concatenate((M3,M0,M1,M2),axis=1)
Mprime0=np.concatenate((M0123,M1230,M2301,M3012),axis=0)
Mprime1=np.concatenate((M1230,M2301,M3012,M0123),axis=0)
zeros=np.zeros(256).reshape(16,16)
Mprime=np.concatenate((np.concatenate((Mprime0,zeros,zeros,zeros),axis=1),np.concatenate((zeros,Mprime1,zeros,zeros),axis=1),np.concatenate((zeros,zeros,Mprime1,zeros),axis=1),np.concatenate((zeros,zeros,zeros,Mprime0),axis=1)),axis=0)
print(rc3,rc2,rc1,sep='\n')
print(Mprime)

[0, 8, 2, 14, 15, 10, 9, 8, 14, 12, 4, 14, 6, 12, 8, 9]
[10, 4, 0, 9, 3, 8, 2, 2, 2, 9, 9, 15, 3, 1, 13, 0]
[1, 3, 1, 9, 8, 10, 2, 14, 0, 3, 7, 0, 7, 3, 4, 4]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [21]:
def S(x):
    before=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
    after=[11,15,3,2,10,12,9,1,6,7,8,0,14,5,13,4]
    return(after[before.index(x)])
def invS(x):
    before=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
    after=[11,15,3,2,10,12,9,1,6,7,8,0,14,5,13,4]
    return(before[after.index(x)])

In [22]:
k1k0=[[] for i in range(16)]
for sets in range(5):
    for n in range(16):
        cand=[]
        for i in range(16):
            sigma=0
            for j in range(16):
                sigma=sigma^S(c1[16*sets+j][n]^rc3[n]^i)
            if sigma==0:
                cand.append(i)
        k1k0[n].append(cand)
#print(k1k0)
for i in range(16):
    cand=set(k1k0[i][0])
    for j in range(1,len(k1k0[i])):
        cand=cand&set(k1k0[i][j])
    k1k0[i]=cand.pop()
print(k1k0)

[12, 1, 5, 10, 4, 11, 12, 8, 5, 5, 5, 5, 4, 8, 4, 11]


In [24]:
peeloff=ct.copy()
for i in range(len(peeloff)):
    peeloff[i]=['0x'+j for j in peeloff[i]]
    temp=''
    for j in range(16):
        temp=temp+str(bin(S(int(eval(peeloff[i][j]))^rc3[j]^k1k0[j])))[2:].zfill(4)
    peeloff[i]=list(map(str,list(map(int,((np.array(list(map(int,list(temp))))@Mprime)%2).tolist()))))
    temp=[]
    for j in range(16):
        temp.append(eval('0b'+''.join(peeloff[i][4*j:4*j+4])))
    peeloff[i]=[temp[0],temp[5],temp[10],temp[15],temp[4],temp[9],temp[14],
                temp[3],temp[8],temp[13],temp[2],temp[7],temp[12],temp[1],temp[6],temp[11]]
print(peeloff[:256])

[[3, 12, 10, 2, 9, 3, 12, 12, 11, 9, 12, 0, 11, 12, 1, 8], [3, 12, 10, 2, 13, 6, 10, 0, 9, 9, 13, 13, 3, 14, 7, 7], [0, 12, 14, 6, 9, 3, 12, 12, 15, 2, 7, 0, 15, 12, 5, 7], [0, 14, 15, 7, 10, 3, 4, 13, 15, 2, 7, 0, 15, 15, 15, 13], [11, 6, 10, 10, 10, 3, 4, 13, 11, 9, 12, 0, 9, 4, 12, 9], [10, 6, 14, 13, 5, 4, 11, 13, 10, 13, 13, 5, 3, 4, 4, 13], [10, 10, 15, 12, 2, 9, 9, 9, 9, 14, 8, 2, 11, 12, 1, 8], [15, 2, 11, 12, 2, 9, 9, 9, 3, 10, 2, 2, 15, 12, 5, 7], [0, 14, 15, 7, 13, 4, 8, 12, 14, 5, 7, 4, 6, 13, 4, 10], [0, 12, 14, 6, 13, 6, 10, 0, 14, 5, 7, 4, 7, 0, 15, 10], [10, 6, 14, 13, 5, 6, 0, 1, 9, 14, 8, 2, 9, 4, 12, 9], [13, 2, 8, 14, 5, 6, 0, 1, 3, 10, 2, 2, 15, 15, 15, 13], [11, 6, 10, 10, 13, 4, 8, 12, 9, 9, 13, 13, 3, 4, 4, 13], [15, 2, 11, 12, 4, 0, 11, 2, 11, 14, 4, 9, 7, 0, 15, 10], [10, 10, 15, 12, 4, 0, 11, 2, 10, 13, 13, 5, 3, 14, 7, 7], [13, 2, 8, 14, 5, 4, 11, 13, 11, 14, 4, 9, 6, 13, 4, 10], [11, 6, 10, 10, 2, 8, 4, 2, 2, 11, 2, 1, 11, 12, 1, 8], [11, 10, 7, 14, 2, 8, 4

In [26]:
p2=[]
for i in range(20480//256):
    for j in range(16):
        p2.append(pt[256*i+224+j])
for i in range(len(p2)):
    p2[i]=['0x'+j for j in p2[i]]
    for j in range(16):
        p2[i][j]=int(eval(p2[i][j]))
print(p2)

[[0, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 2, 9], [1, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 2, 9], [2, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 2, 9], [3, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 2, 9], [4, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 2, 9], [5, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 2, 9], [6, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 2, 9], [7, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 2, 9], [8, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 2, 9], [9, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 2, 9], [10, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 2, 9], [11, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 2, 9], [12, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 2, 9], [13, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 2, 9], [14, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 2, 9], [15, 14, 13, 6, 6, 12, 14, 1, 8, 4, 11, 14, 2, 3, 2, 9], [0, 11, 14, 9, 11, 11, 15, 1, 15, 1, 4, 9, 9, 0, 5, 2], [1, 11, 14, 9, 11, 11, 15, 1, 15, 1, 4, 9

In [27]:
c2=[]
for i in range(20480//256):
    for j in range(16):
        c2.append(peeloff[256*i+224+j])
print(c2)

[[4, 8, 14, 1, 7, 6, 6, 15, 0, 10, 10, 4, 14, 7, 0, 8], [15, 8, 5, 5, 15, 2, 6, 8, 7, 10, 0, 0, 14, 7, 0, 8], [15, 0, 2, 4, 15, 10, 1, 2, 15, 2, 7, 0, 3, 14, 5, 12], [15, 8, 5, 5, 15, 10, 1, 2, 12, 14, 0, 8, 14, 15, 15, 7], [0, 15, 10, 2, 6, 4, 7, 15, 0, 6, 1, 5, 2, 4, 15, 12], [15, 0, 2, 4, 15, 2, 6, 8, 14, 3, 14, 5, 15, 6, 1, 8], [2, 14, 15, 6, 9, 3, 12, 12, 12, 14, 0, 8, 4, 4, 6, 3], [2, 14, 15, 6, 13, 4, 12, 4, 7, 10, 0, 0, 4, 11, 14, 2], [4, 8, 14, 1, 6, 14, 5, 11, 12, 12, 2, 12, 14, 15, 15, 7], [5, 13, 7, 11, 6, 14, 5, 11, 7, 6, 2, 13, 3, 14, 5, 12], [0, 12, 14, 6, 9, 3, 12, 12, 15, 2, 7, 0, 15, 12, 5, 7], [0, 12, 14, 6, 13, 4, 12, 4, 14, 3, 14, 5, 2, 4, 15, 12], [5, 9, 15, 1, 12, 6, 13, 4, 12, 12, 2, 12, 4, 4, 6, 3], [5, 13, 7, 11, 7, 6, 6, 15, 0, 6, 1, 5, 15, 6, 1, 8], [0, 15, 10, 2, 12, 6, 13, 4, 7, 6, 2, 13, 15, 12, 5, 7], [5, 9, 15, 1, 6, 4, 7, 15, 0, 10, 10, 4, 4, 11, 14, 2], [9, 9, 7, 3, 10, 1, 7, 5, 15, 13, 12, 9, 2, 3, 4, 12], [7, 4, 15, 15, 10, 0, 5, 7, 11, 1, 13, 10, 2

In [ ]:
k1=[[] for i in range(4)]
nibbles=[[8,1,1,1],[1,1,1,8],[1,1,8,1],[1,8,1,1]]
for rows in range(4):
    cand=[]
    for i in range(16**4):
        round2=[]
        i16=np.array([i//(16**3),(i%16**3)//(16**2),(i%16**2)//16,i%16])
        for j in range(16):
            peelinvS=list(map(S,(np.array(c2[j][4*rows:4*rows+4])^np.array(rc2[4*rows:4*rows+4])^i16).tolist()))
            peelMprime=''
            for k in range(4):
                peelMprime=peelMprime+(''.join(list(str(bin(peelinvS[k]))[2:].zfill(4))))
            peelMprime=np.array(list(map(int,peelMprime)))
            if rows==0 or rows==3:
                peelMprime=list(map(str,((peelMprime@Mprime0)%2).tolist()))
            else:
                peelMprime=list(map(str,((peelMprime@Mprime1)%2).tolist()))
            peelS=np.array(list(map(invS,list(map(eval,['0b'+''.join(peelMprime[4*k:4*k+4]) for k in range(4)])))))
            peelS=(peelS^i16^np.array(rc1[4*rows:4*rows+4])).tolist()
            round2.append(peelS)
            #print(round2)
        cnt=[len(set(round2[k][j] for k in range(len(round2)))) for j in range(4)]
        if cnt==nibbles[rows]:
            cand.append(i16.tolist())
    k1[rows].append(cand)
print(k1)

[[[[7, 5, 6, 7]]], [[[7, 3, 7, 5]]], [[[6, 8, 6, 3]]], [[[7, 0, 7, 2]]]]


In [ ]:
k1=[7,5,6,7,7,3,7,5,6,8,6,3,7,0,7,2]
k0_prime=(np.array(k1k0)^np.array(k1)).tolist()
print(k0_prime)

[11, 4, 3, 13, 3, 8, 11, 13, 3, 13, 3, 6, 3, 8, 3, 9]


In [ ]:
k0_bin=[]
for i in range(16):
    k0_bin=k0_bin+(list(bin(k0_prime[i])[2:].zfill(4)))
k0_bin=list(map(int,k0_bin))
k0_bin=k0_bin[1:63]+[k0_bin[1]^k0_bin[63]]+[k0_bin[0]]
k0_bin=list(map(str,k0_bin))
k0=[]
for i in range(16):
    k0.append('0b'+''.join(k0_bin[4*i:4*i+4]))
    k0[i]=int(eval(k0[i]))
print(k0)

[6, 8, 7, 10, 7, 1, 7, 10, 7, 10, 6, 12, 7, 0, 7, 3]


In [ ]:
# PRINCE_encryption (https://christopherdare.com/code/prince#EncryptionCode)

from __future__ import print_function

###########################################
#           PRIVATE VARIABLES             #
###########################################

# Substitution box used on individual nibbles
SBox = [0x0B, 0x0F, 0x03, 0x02, 0x0A, 0x0C, 0x09, 0x01, 0x06, 0x07, 0x08, 0x00, 0x0E, 0x05, 0x0D, 0x04]
# Inverse substitution box used on individual nibbles
InvSBox = [0x0B, 0x07, 0x03, 0x02, 0x0F, 0x0D, 0x08, 0x09, 0x0A, 0x06, 0x04, 0x00, 0x05, 0x0E, 0x0C, 0x01]

# Each of our 11 64-bit round constants broken up as a series of 8 bytes
RC = [
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x31, 0x91, 0xa8, 0xe2, 0x30, 0x07, 0x37, 0x44,
    0x4a, 0x90, 0x83, 0x22, 0x92, 0xf9, 0x13, 0x0d,
    0x80, 0xe2, 0xaf, 0x89, 0xce, 0xe4, 0xc6, 0x98,
    0x54, 0x82, 0x12, 0x6e, 0x83, 0x0d, 0x31, 0x77,
    0xeb, 0x45, 0x66, 0xfc, 0x43, 0x9e, 0xc0, 0xc6,
    0xe7, 0x8f, 0xf4, 0x87, 0xdf, 0x59, 0xc5, 0x1b,
    0x58, 0x48, 0x80, 0x15, 0x1f, 0xca, 0x34, 0xaa,
    0x8c, 0x28, 0x3d, 0xf2, 0x52, 0x23, 0xc3, 0x45,
    0x46, 0x5a, 0x11, 0x59, 0x0e, 0x3e, 0x16, 0xd0,
    0x3d, 0x5b, 0x3a, 0x99, 0xac, 0xc0, 0x32, 0x99,
    0x0c, 0xca, 0x92, 0x7b, 0x9c, 0xc7, 0x05, 0xdd
]

###########################################
#            PRIMARY FUNCTIONS            #
###########################################

def cipher(ExtendedKey):
    """ The complete PRINCE forward encryption on the 64-bit state performed through nibble calculations """
    global _State

    # key whitening with k_0
    _State = [_State[i] ^ ExtendedKey[i] for i in range(8)]

    # beginning of actual cipher
    _AddKey(ExtendedKey)
    _AddRoundConstant(0)
    print("Round 0")
    for i in range(8):
        print(format(_State[i], '02x'), end=' ')
    print()

    # five forward rounds -> two forward rounds
    for i in range(1, 2): # range(1, 6)
        _SubNibbles()
        _MLayer()
        _AddRoundConstant(i)
        _AddKey(ExtendedKey)

        print("Round " + str(i))
        for i in range(8):
            print(format(_State[i], '02x'), end=' ')
        print()

    # middle round
    _SubNibbles()
    _MPrimeLayer()
    _InvSubNibbles()

    # five inverse rounds -> two inverse rounds
    for i in range(2, 3): # range(6, 11)
        _AddKey(ExtendedKey)
        _AddRoundConstant(i)
        _InvMLayer()
        _InvSubNibbles()

        print("Round " + str(i))
        for i in range(8):
            print(format(_State[i], '02x'), end=' ')
        print()


    _AddRoundConstant(3) # _AddRoundConstant(11)
    _AddKey(ExtendedKey)
    # end of actual cipher

    # key whitening with k'_0
    _State = [_State[i] ^ ExtendedKey[i+8] for i in range(8)]



def ExtendKey(Key):
    """ PRINCE's version of a key schedule, which extends our 128-bit key to a 192-bit key """
    newKey = [0x00] * 24

    for i in range(8):
        # k_0 stays the same
        newKey[i] = Key[i]
        # k'_0 is a k_0 rotated right one bit and XORed with the last bit
        newKey[i + 8] = (Key[i] >> 1) | (Key[(i + 1) % 8] >> 7) #WRONG CODE
        # k_1 stays the same
        newKey[i + 16] = Key[i + 8]

    newKey[15] ^= (Key[7] & 0x10)

    return newKey


###########################################
#             HELPER FUNCTIONS            #
###########################################

def _ShiftRows():
    """ Helper method which distinguishes our two linear layers M from M' """
    global _State

    temp = _State[:] # copy the state into a temporary holder
    perm = [0, 5, 2, 7, 4, 1, 6, 3]

    _State = [ (temp[perm[i]] & 0x0F) | (_State[perm[(i+2)%8]] & 0xF0) for i in range(8)]


def _InvShiftRows():
    """ Inverse of our ShiftRows() function which allows us to distinguish M'^-1 from M^-1 """
    global _State

    temp = _State[:] # copy the state into a temporary holder
    perm = [0, 5, 2, 7, 4, 1, 6, 3]

    _State = [ (temp[perm[i]] & 0x0F) | (_State[perm[(i+6)%8]] & 0xF0) for i in range(8)]


def _SubNibbles():
    """ Send the state through a substitution layer nibble-by-nibble """
    global _State
    _State = [ (SBox[_State[i] >> 4] << 4) | SBox[_State[i] & 0x0F] for i in range(8) ]


def _InvSubNibbles():
    """ Inverse of our substitution layer which sends each substituted nibble back to the original nibble """
    global _State
    _State = [ (InvSBox[_State[i] >> 4] << 4) | InvSBox[_State[i] & 0x0F] for i in range(8) ]


def _MPrimeLayer():
    """ Our linear layer, designed to use as little space as possible and prevent wasted clock-cycles. Recall that this method is in fact its own inverse. """
    global _State

    # M0
    temp = _State[0] # we only need 1 storage variable here
    _State[0] = (temp & 0xD7) ^ (_State[1] & 0x7D) ^ (temp >> 4 & 0x0B) ^ (_State[1] >> 4 & 0x0E) ^ (temp << 4 & 0xB0) ^ (_State[1] << 4 & 0xE0)
    _State[1] = (temp & 0x7D) ^ (_State[1] & 0xD7) ^ (temp >> 4 & 0x0E) ^ (_State[1] >> 4 & 0x0B) ^ (temp << 4 & 0xE0) ^ (_State[1] << 4 & 0xB0)
    # M1
    temp = _State[2]
    _State[2] = (temp & 0xEB) ^ (_State[3] & 0xBE) ^ (temp >> 4 & 0x0D) ^ (_State[3] >> 4 & 0x07) ^ (temp << 4 & 0xD0) ^ (_State[3] << 4 & 0x70)
    _State[3] = (temp & 0xBE) ^ (_State[3] & 0xEB) ^ (temp >> 4 & 0x07) ^ (_State[3] >> 4 & 0x0D) ^ (temp << 4 & 0x70) ^ (_State[3] << 4 & 0xD0)
    # M1
    temp = _State[4]
    _State[4] = (temp & 0xEB) ^ (_State[5] & 0xBE) ^ (temp >> 4 & 0x0D) ^ (_State[5] >> 4 & 0x07) ^ (temp << 4 & 0xD0) ^ (_State[5] << 4 & 0x70)
    _State[5] = (temp & 0xBE) ^ (_State[5] & 0xEB) ^ (temp >> 4 & 0x07) ^ (_State[5] >> 4 & 0x0D) ^ (temp << 4 & 0x70) ^ (_State[5] << 4 & 0xD0)
    # M0
    temp = _State[6]
    _State[6] = (temp & 0xD7) ^ (_State[7] & 0x7D) ^ (temp >> 4 & 0x0B) ^ (_State[7] >> 4 & 0x0E) ^ (temp << 4 & 0xB0) ^ (_State[7] << 4 & 0xE0)
    _State[7] = (temp & 0x7D) ^ (_State[7] & 0xD7) ^ (temp >> 4 & 0x0E) ^ (_State[7] >> 4 & 0x0B) ^ (temp << 4 & 0xE0) ^ (_State[7] << 4 & 0xB0)

def _MLayer():
    """ The adjusted linear layer which is utilized each regular round """
    _MPrimeLayer()
    _ShiftRows()

def _InvMLayer():
    """ The inverse adjusted linear layer which is utilized each inverse regular round """
    _InvShiftRows()
    _MPrimeLayer()

def _AddRoundConstant(round):
    """ Function which simply applies a given round's constant to the state """
    global _State
    _State = [ _State[i] ^ RC[8 * round + i] for i in range(8)]

def _AddKey(ExtendedKey):
    """ Function which adds k_1 to the state """
    global _State
    _State = [ _State[i] ^ ExtendedKey[i + 16] for i in range(8) ]


In [ ]:
###########################################
#             TEST VECTORS                #
###########################################

# state in the form [10,32,54,76,98,ba,dc,fe] for nibble ordering in array
# plaintext 0123456789ABCDEF -> _State 1032547698BADCFE
# key 0123456789ABCDEF(k0) / FEDCBA9876543210(k1) -> Key 1032547698BADCFE(k0) / EFCDAB8967452301(k1)
_State = [0xF0, 0x8D, 0x6A, 0x8C, 0xD9, 0xBD, 0x6C, 0x65] # plaintext 0fd8a6c89ddbc656
Key = [0x86, 0xA7, 0x17, 0xA7, 0xA7, 0xC6, 0x07, 0x37, 0x57, 0x76, 0x37, 0x57, 0x86, 0x36, 0x07, 0x27] # k0, k1

if __name__ == "__main__":
    #ExtendedKey = ExtendKey(Key) # Save the extended key
    #print(ExtendedKey)
    ExtendedKey=[0x86, 0xA7, 0x17, 0xA7, 0xA7, 0xC6, 0x07, 0x37,
                 0x4B, 0xD3, 0x83, 0xDB, 0xD3, 0x63, 0x83, 0x93,
                 0x57, 0x76, 0x37, 0x57, 0x86, 0x36, 0x07, 0x27] #k0, k0', k1
    cipher(ExtendedKey)
    print('0x', end='')
    for i in range(8):
        print(format(_State[i] >> 4 | (_State[i] << 4 & 0xF0), '02x'), end='')
    print() #0591eb8be388be7a

Round 0
21 5c 4a 7c f8 4d 6c 75 
Round 1
32 8c 60 04 56 50 33 f2 
Round 2
cc 5e a5 bd a5 39 a9 8b 
0x0591eb8be388be7a
